"use strict";
exports.__esModule = true;
var single_1 = require("./single");
var employment = new single_1.Employee("Ajith", 22, 20000, "BE");
var deve = new single_1.Dev1("Mani", 24, 40000, "B.TECH");
var t = new single_1.Tester("Bala", 24, 30000, "BE");
var M = new single_1.Manager("Suriya", 34, 60000, "BE");
employment.display();
employment.raisesal();
console.log("employee**********");
deve.display();
deve.raisesal1();
console.log("devloper**********");
t.display();
t.raisesal2();
console.log("tester**********");
M.display();
M.raisesal3();
console.log("manager**********");
